### ISSUE TITLE
Getting a Type Error

### ISSUE THREAD

**Issue by mzfr** [hellman/xortool#17]
When I try to use the `-c` or `-b` or `-o` parameter I am getting a Type Error saying:
```
➜ xortool encrypted -l 9 -o
Traceback (most recent call last):
  File "/bin/xortool", line 381, in <module>
    main()
  File "/bin/xortool", line 68, in main
    key_char_used) = guess_probable_keys_for_chars(ciphertext, try_chars)
  File "/bin/xortool", line 252, in guess_probable_keys_for_chars
    keys = guess_keys(text, c)
  File "/bin/xortool", line 274, in guess_keys
    key_possible_bytes[offset].append(chr(ord(char) ^ most_char))
TypeError: ord() expected string of length 1, but int found
``` 

I have tried to use it like `xortool encrypted -l 9 -c 00`. 
Also tried `xortool encrypted -l 9 -c 20` but it all results in the Type error

**Comment by littercorporal** [comment]
same as you

**Comment by fenchelfen** [comment]
Have the same issue. Has it been solved?

**Comment by damaoooo** [comment]
I have the same problem,maybe i should change the source code

**Comment by maage** [comment]
Also #26 fixes this issue.

**Comment by hellman** [comment]
I think should work now
