### ISSUE TITLE
xortool-xor is not python 3 compatible

### ISSUE THREAD

**Issue by duanehutchins** [hellman/xortool#21]
```
Traceback (most recent call last):
  File "/python/bin/xortool-xor", line 117, in <module>
    main()
  File "/python/bin/xortool-xor", line 51, in main
    sys.stdout.write(xor(datas, nocycle=nocycle))
  File "/python/bin/xortool-xor", line 66, in xor
    for i in xrange(maxlen):
NameError: name 'xrange' is not defined
```

`xrange` was replaced by `range` in Python 3

**Comment by duanehutchins** [comment]
added PR #23 to fix issue

**Comment by maage** [comment]
Also #26 fixes this issue.

**Comment by hellman** [comment]
Thanks, should be working now

**Comment by anthraxx** [comment]
@hellman would it be possible to actually cut a python3 release? It would be great as lot of distros are moving away from python2 and I would like to put this into the main repos.
