### ISSUE TITLE
error under kali

### ISSUE THREAD

**Issue by sh1va73** [hellman/xortool#29]
My command under latest Kali is: 
xortool -x -c ' ' xor.hex

The error i get is:
Traceback (most recent call last):
  File "/usr/local/bin/xortool", line 396, in <module>
    main()
  File "/usr/local/bin/xortool", line 65, in main
    ciphertext = get_ciphertext()
  File "/usr/local/bin/xortool", line 108, in get_ciphertext
    ciphertext = decode_from_hex(ciphertext)
  File "/usr/local/lib/python2.7/dist-packages/xortool/routine.py", line 56, in decode_from_hex
    return bytes.fromhex(only_hex_digits)
AttributeError: type object 'str' has no attribute 'fromhex'

**Comment by hellman** [comment]
xortool now runs only on python3; please uninstall old versions of xortool and install using installation command from readme (using python3)
