### ISSUE TITLE
Dependency on 'importlib_metadata' missing

### ISSUE THREAD

**Issue by cweiske** [hellman/xortool#34]
I did a simple "pip3 install xortool" and then tried to execute it:

```
$ xortool --help
Traceback (most recent call last):
  File "/usr/local/bin/xortool", line 5, in <module>
    from xortool.tool_main import main
  File "/usr/local/lib/python3.8/dist-packages/xortool/__init__.py", line 1, in <module>
    from importlib_metadata import version
ModuleNotFoundError: No module named 'importlib_metadata'
```

After manually installing `importlib-metadata` it works.

So it seems the dependency is missing, and pip3 does not automatically install that.

**Comment by hellman** [comment]
Thank you, fixed!

**Comment by cweiske** [comment]
Thank you for the quick fix, and for making xortool!
