### ISSUE TITLE
error after running bruteforce

### ISSUE THREAD

**Issue by vreaw** [hellman/xortool#41]
The most probable key lengths:
 2:  13.3%
 4:  15.2%
 6:  11.4%
 8:  13.8%
10:   7.3%
12:   9.4%
14:   7.7%
16:  11.7%
24:   5.0%
32:   5.3%
Key-length can be 4*n
256 possible key(s) of length 4:
2104
3015
0326
1237
6540
...
Traceback (most recent call last):
  File "/home/vrea/.local/bin/xortool", line 8, in <module>
    sys.exit(main())
  File "/home/vrea/.local/lib/python3.8/site-packages/xortool/tool_main.py", line 105, in main
    produce_plaintexts(ciphertext, probable_keys, key_char_used)
  File "/home/vrea/.local/lib/python3.8/site-packages/xortool/tool_main.py", line 397, in produce_plaintexts
    print(fmt.format(count_valid, round(threshold_valid), **COLORS))
ValueError: expected '}' before end of string

**Comment by hellman** [comment]
Should be fixed in v1.0.2
