### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by MarioVilas** [hellman/xortool#49]
There appears to be a missing dependency, since I see this error when trying to run xortool on a fresh install using pip:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/xortool", line 5, in <module>
    from xortool.tool_main import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/xortool/__init__.py", line 1, in <module>
    from importlib_metadata import version
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by hellman** [comment]
The latest version should fix this. Let me know if not
